services:
  postgres:
    image: 'postgres:latest'
    environment:
#       Nome padrão do BD: postgres
#       Nome padrão do Usuário: postgres
#       Como o password é o único que é obrigatório, foi definido assim:
      - 'POSTGRES_PASSWORD=${BD_ACESS_PASS}'
        #na meu BD local, coloquei como "postgre"
    ports:
      - '5432:5432'
